name: vegetables_firestore
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  dart_mappable: ^4.2.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  dart_mappable_builder: ^4.2.3
  build_runner: ^2.4.13
  json_schema: ^5.1.3
